package com.example.tictactoe.game;

public enum WinLine {
    TOP_HORIZONTAL,
    MIDDLE_HORIZONTAL,
    BOTTOM_HORIZONTAL,
    LEFT_VERTICAL,
    MIDDLE_VERTICAL,
    RIGHT_VERTICAL,
    LEFT_TO_RIGHT_DIAGONAL,
    RIGHT_TO_LEFT_DIAGONAL;
}
